name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Show tag
        run: |
          echo "Tag detected: $GITHUB_REF"
          echo "Tag name: ${GITHUB_REF#refs/tags/}"
